from .generators import histogram_generator, correlation_histogram_generator
from .wasserstein_distance import wasserstein_distance_1d, wasserstein_distance_2d
from .chi_square import chi_square_distance
from .compare_correlation import compare_correlation
from .compare_histogram_1d import compare_histogram_1d 

