import requests
import json
import logging
import os
import threading

script_path = os.path.dirname(os.path.realpath(__file__))
telegram_config_path = os.path.join(script_path, "telegram.json")
config = dict()
try:
    with open(telegram_config_path, "r") as fp:
        config = json.load(fp)
except:
    if "TELEGRAM_BOT_TOKEN" in os.environ and "TELEGRAM_BOT_CHAT_ID" in os.environ:
        config = {
                "api-token": os.environ["TELEGRAM_BOT_TOKEN"],
                "chat-id": os.environ["TELEGRAM_BOT_CHAT_ID"],
        }
        with open(telegram_config_path, "w") as fp:
            json.dump(config, fp, indent=4)


def send_to_bot(message, token, chatid):
    """Send a message to a Telegram-Bot.

    Paramters
    ---------
    message : str
        Chat message that should be sent to the bot.
    token : str
        Telegram-Bot token.
    chatid : str
        ChatID for the message. The ChatID can be gathered by having a human
        chat with the bot and then running

        curl -X POST https://api.telegram.org/botTOKEN/getUpdates

        where TOKEN should be replaced with the bot token.

    Returns
    -------
    retval : str
        JSON reponse payload which has been gathered by requests.get(...).
    """
    try:
        text = "https://api.telegram.org/bot" \
                + token \
                + "/sendMessage?chat_id=" \
                + chatid \
                + "&text=" \
                + message
        response = requests.get(text, timeout=5)
        retval = response.json()
    except:
        retval = None

    return retval


class TelegramHandler(logging.StreamHandler):
    """A logging.StreamHandler which handles log dispatching to a Telegram-Bot."""

    def __init__(self, *args, **kwargs):
        """Construct a logging.StreamHandler which sends messages to a bot.

        This StreamHandler relies on the contents of api-token and chat-id in
        src/utils/telegram.py. They get generated by either environment
        variables or a telegram.json file in src/utils. For more details
        look at the source code! The communication happens in a seperate
        thread (python threading module) and is therefore non-blocking.

        Parameters
        ----------
        See logging.StreamHandler
        """
        super().__init__(*args, **kwargs)
        self.token = config.get("api-token", None)
        self.chatid = config.get("chat-id", None)

        if self.token is not None and self.chatid is not None:
            self.useable = True
        else:
            self.useable = False

    def emit(self, record):
        """Format message and send it to the bot.

        This function gets called by an attached logger. The communication
        with the bot happens inside a thread (python threading module) and
        will therefore not block execution.

        Parameters
        ----------
        record : logging.LogRecord
            Record of the dispatched log message.
        """
        if self.useable:
            message = self.format(record)

            thread = threading.Thread(
                    target=send_to_bot,
                    args=(message, self.token, self.chatid))

            thread.setDaemon(True)
            thread.start()

